server:
  port: 8888
  address: 127.0.0.1

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:${CONFIG_REPO_PATH:../../config-repo}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,prometheus
